### ISSUE TITLE
what 's the rtf on cpu?

### ISSUE THREAD

**Issue by hdmjdp** [lmnt-com/diffwave#12]
In your code the T=50?

**Comment by hdmjdp** [comment]
I have tested it on cpu. It is too slow compared to wavegan. what is the reason?

**Comment by sharvil** [comment]
DiffWave and WaveGAN are different models each with their own advantages and disadvantages. If you're looking for a high-quality vocoder with faster-than-realtime synthesis on CPU, your best bet is WaveRNN.
