### ISSUE TITLE
Error in version comparison in dataset.py

### ISSUE THREAD

**Issue by m-hamza-mughal** [lmnt-com/diffwave#17]
Hi. 
Thankyou for your great work.

I believe, there can be a better way to compare versions of torchaudio. Instead of comparing strings, we can use packages like [packaging](https://pypi.org/project/packaging/) and use functions like `parse` from `packaging.version` to properly compare versions. 

To reproduce this error, you can use the installation of `torchaudio==0.10.0` and run the training using that. 
`'0.10.0' > '0.7.0'` gives `False` which is incorrect.

https://github.com/lmnt-com/diffwave/blob/9ad64429b0052c8d51a5befd26354086c4ef47fe/src/diffwave/dataset.py#L39

**Comment by sharvil** [comment]
That's an excellent suggestion. Any chance you could send over a PR to fix this problem? If not, I'll eventually get to it. :)

**Comment by sharvil** [comment]
Fixed by updating min torchaudio to 0.9.0 and removing the version checks.
