### ISSUE TITLE
The audio have some noise.

### ISSUE THREAD

**Issue by Ziyan0829** [lmnt-com/diffwave#25]
Hi, thanks for your good job. 
I trained the model on a single speaker dataset which have 10000 utterances,  loss is shown in figure. In inference, the audio have some clearly noise,  is this dataset  too small? Or are there other reasons?
![捕获](https://user-images.githubusercontent.com/44149888/157783573-fa7b1088-893b-4f57-8f98-7f2ca5a47924.PNG)
…]()

**Comment by sharvil** [comment]
The training loss you're getting on your dataset seems higher than what we get out of LJSpeech. Here are some questions that might help get us to better results:

- Are there large chunks of silence or silences at the beginning/end of utterances?
- How long are the utterances (LJSpeech is ~6.5s / utterance)?
- Are you using the fast sampling procedure or the standard one?
- Are you able to share some samples to get a better idea of what kind of noise is audible?

**Comment by Ziyan0829** [comment]
1. There no large chunks of silence at the beginning/end of utterances.
2. My datasat is ~2~4s/utterance.
3. I used the fast sampling procedure in my inference.
I'm sorry that i try to upload the samples but it's failed . It sounds like a gaussian noise, clearly at the begining, and then it gets weaker,  eventually the sound gradually becomes unstable(Some jitter).

**Comment by Ziyan0829** [comment]
1.There no large chunks of silence at the beginning/end of utterances.
2.My datasat is 2~4s/utterance.
3.I used the fast sampling procedure in my inference.
I'm sorry that i try to upload the samples but it's failed . It sounds like a gaussian noise, clearly at the begining, and then it gets weaker, eventually the sound gradually becomes unstable(Some jitter).

**Comment by wangfn** [comment]
@sharvil Thank you for the excellent work. I have a similar issue with the residual gaussian noise in the generated speech files, even without the fast sampling. One example is attached. The dataset used is similar to the one used by @Ziyan0829, however, there're few frames of purely 0s at both the beginning and end of each speech file. Might this be the reason?
[sample.zip](https://github.com/lmnt-com/diffwave/files/8333825/sample.zip)

**Comment by sharvil** [comment]
I listened to the sample. My best assessment is that the default noise schedule doesn't work well with your dataset. You may need to add more denoising steps and reduce the noise variance at the lower endpoint (i.e. reduce 1e-4 in the noise schedule).

**Comment by wangfn** [comment]
Thank you for the reply. Mmh, it makes sense. I'll try a noise schedule with 1e-4 reduced.
