### ISSUE TITLE
Pretrained weights and audio samples are not accessible

### ISSUE THREAD

**Issue by jasonkhadka** [lmnt-com/diffwave#36]
I tried 
https://lmnt.com/assets/diffwave/diffwave-ljspeech-22kHz-1000578.pt
and
https://lmnt.com/assets/diffwave

and seems like both are down.

**Comment by sharvil** [comment]
Just tried locally and from a remote machine -- seems like it's working fine on my end. Monitoring seems to indicate everything's working right too. There were some DNS changes a few days ago, maybe you need to flush your DNS cache.
