### ISSUE TITLE
About spectrogram = # get your hands on a spectrogram in [N,C,W] format

### ISSUE THREAD

**Issue by paklau99988** [lmnt-com/diffwave#4]
How generate spectogram?

**Comment by sharvil** [comment]
One good way to do it is to run the `diffwave.preprocess` module on a wav file (or set of wav files). For example, if you have a wav file like `/path/to/wav/example0.wav`, then you could run:

```sh
python -m diffwave.preprocess /path/to/wav
python -m diffwave.inference /path/to/model /path/to/wav/example0.wav.spec.npy
```
