### ISSUE TITLE
Spectrogram Upsample

### ISSUE THREAD

**Issue by alexdemartos** [lmnt-com/diffwave#6]
Hi,

I'm having trouble with the upsampling of the mel spectrograms. How should I change the ConvTranspose2d kernel, stride and padding to match a hop size of 300? Thank you in advance.

**Comment by sharvil** [comment]
If you're changing the hop size, make sure you also increase `n_fft` to 2048.

For a hop size of 300, you'll want something like this:
```python
self.conv1 = ConvTranspose2d(1, 1, [3, 30], stride=[1, 15], padding=[1, 8], output_padding=[0, 1])
self.conv2 = ConvTranspose2d(1, 1,  [3, 40], stride=[1, 20], padding=[1, 10])
```

**Comment by alexdemartos** [comment]
Thanks very much for your help and fast response ;)
